.PHONY: test clean

build:
	+$(MAKE) -C problem1
	+$(MAKE) -C problem2
	+$(MAKE) -C problem3

test:
	+$(MAKE) -C problem1 test
	+$(MAKE) -C problem2 test
	+$(MAKE) -C problem3 test

clean:
	+$(MAKE) -C problem1 clean
	+$(MAKE) -C problem2 clean
	+$(MAKE) -C problem3 clean